version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tutor_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ege_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: kalsash/tutor-web-app:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ege_db;Username=postgres;Password=1234
      - Jwt__Key=your_super_secret_key_at_least_32_characters_long
    ports:
      - "8080:8080"
    depends_on:
      - postgres 

volumes:
  postgres_data: